src/Frame.cc

hi!
some apps, Java in particular, apparently, change WM_PROPERTY during startup. Pekwm currently disregards this events, and memoizes the protocols a client supports.
This is a bad combination, because it means we never learn about protocol changes. This fix just rereads protocols whenever a corresponding event comes through.
https://youtrack.jetbrains.com/issue/IDEA-197344 describes a problem that occurs without this fix, FWIW.

update list of known protocols when we receive a corresponding PropertyNotify event

---

src/Config.cc

Found this while working on the package, sorry for not doing this before the release.

Fix a typo (Therefor -> Therefore)

---

INSTALL

As pekwm now uses cmake instead of autotools and https://pekwm.org doesn't provide install instructions, I figured I'd update the INSTALL file.
@pekdon What about adding install instructions (also) to the README? As a result they would be visible on the GitHub page of the project.

Update install instructions

---

NEWS.md
src/Action.cc
src/Action.hh
src/ActionHandler.cc
src/AutoProperties.cc
src/CMakeLists.txt
src/Config.cc
src/Config.hh
src/Frame.cc
src/Frame.hh
src/x11.cc
src/x11.hh
test/CMakeLists.txt
test/test_Action.cc
test/test_Config.cc
test/test_Frame.cc
test/test_x11.cc

Support specifying geometry and position in perecentage of the screen/head
in functions that use X11 geometry format such as SetGeometry.
Configuration format:
SetGeometry 100%x50%+0+0 [(current|screen|head-number) [HonourStrut]]
Requested by okraits

Geometry percent

---

doc/actions.md
doc/configuration.md
doc/faq.md

- a few markdown rendering fixes
- I replaced ; with semicolon because on my first reading I thought it
was "separated by either semicolons or dots"
- the FAQ section about mouse configuration is outdated
- new FAQ section about GTK3 apps, quite many of them nowadays

Miscellaneous document updates

---

src/x11.cc

gcc-9.3.0 complains correctly that because 'head' is unsigned, the
comparison is always true. I've checked the caller and it seems all
negative numbers are already handled, so we should always get a good
positive number in here.

Fix -Wsign-compare in X11.cc

---

src/Completer.cc
src/Config.cc
src/Util.cc
src/Util.hh
src/WindowManager.cc
src/main.cc
test/system/all.plux

Wrap getenv in Util to return a std::string for simpler (and less
dangerous) code.

Cleanup in main.cc, introduce Util::getEnv

---

CMakeLists.txt
contrib/CMakeLists.txt
contrib/lobo/CMakeLists.txt
data/CMakeLists.txt
data/scripts/CMakeLists.txt
data/themes/CMakeLists.txt
data/themes/default-plain/CMakeLists.txt
data/themes/default/CMakeLists.txt
data/themes/pion/CMakeLists.txt
doc/CMakeLists.txt
src/CMakeLists.txt

CMake < 2.8.12 support has been deprecated in recent CMake versions.
Judging from the CMake site 3.5 should be a safe version to get support
from most recent Linux distributions.
Thanks biopsin for reporting. Closing #28

Bump minimum required CMake version to 3.5

---

NEWS.md
src/Frame.cc
src/Frame.hh
src/WindowManager.cc
test/CMakeLists.txt
test/system/CMakeLists.txt
test/system/all.plux
test/system/test_client.cc
test/system/test_update_client_list.cc

Regression introduced with the start of focus stealing prevention where
the client list was not updated when a new client was created.

Fix regression not updating client lists on new Frames (Closing #7)

---

NEWS.md
src/CmdDialog.cc
src/CmdDialog.hh
src/Completer.cc
src/Completer.hh

Speed up startup, use less memory at the expense of slower CmdDialog
displaying by not building the CmdDialog cache for paths on startup.
Build it on map effectively keeping an up-to-date list of available
commands and clear the list when it is unmapped.

Don't keep path cache around for the CmdDialog, refresh on map

---

src/ActionHandler.cc
src/ActionHandler.hh
src/Client.cc
src/Frame.cc
src/Harbour.cc
src/Harbour.hh
src/ManagerWindows.cc
src/ManagerWindows.hh
src/PDecor.cc
src/WinLayouter.cc
src/WindowManager.cc
src/WindowManager.hh
src/Workspaces.cc
src/pekwm.cc
src/x11.cc
src/x11.hh

Move Harbour, CmdDialog, SearchDialog, HintWO and RootWO from
WindowManager into the pekwm namespace and ActionHandler.
While at it, moved Strut information out from namespace x11 and into
RootWO.

Move more resources out of WindowManager

---

doc/configuration.md

This is added in 3732e07 (Add background support to pekwm themes,
2021-01-16) and is mentioned in themes.md, but would be nice to be
listed in configuration.md as well

Mention ThemeBackground in configuration.md

---

doc/actions.md
src/Action.hh
src/Config.cc
src/PDecor.cc
src/PDecor.hh
test/CMakeLists.txt
test/system/test_update_client_list.cc
test/test_Config.cc

This adds support for '%' to the move/resize commands, which I think is in line with SetGeometry accepting '%' elsewhere. The first three commits are actually (good I think) cleanup. The meat is in the last one. I don't have multiple monitor setup to test though (and I think those "heads" are about that).
My first time making real changes in pekwm, let me know if I did anything wrong, I can try to fix it.

Move resize in percentage

---

src/WindowManager.cc

The config key is parsed and obtainable via getThemeBackground()
call. But it's never called. So whatever you set in config file, theme
background is always used.

Do not start pekwm_bg when ThemeBackground is set to false

---

doc/actions.md

Since issue #13, the geometry string can now take percent in both size
and position. I elaborate the "XParseGeometry can parse" a bit because
it seems less friendly to make non-developer user go look up what it is
The command also accepts "screen" or "current" in the second parameter
instead of just plain number.
The third new option, HonourStruct, I don't really know what it is and
not familiar enough with pekwm code base to figure it out myself, so I
left it undocumented.

Document new SetGeometry command

---

doc/faq.md

This line is to separate the header and footer from the rest. I didn't
notice this when I added a new faq entry, after it instead of before it.

Move the horz line down to bottom in faq.md

---

data/keys
doc/configuration.md

This is the second point of issue #56. But instead of selectively
switching a few Ctrl-Mod1 chain to Ctrl-Mod4, I think that would just
cause more confusion. Ctrl-Mod1 chain does cause trouble (at least the
Ctrl-Mod1-S in emacs).
I've been using these new keybindings for a couple days. Not so
bad. Losing the ability to use the right Alt (with right hand) could be
a problem to some people. But I have personally not seen a problem with
it.

Update global keys to use Ctrl Mod4 chains instead of Ctrl Mod1

---

doc/actions.md
src/ActionHandler.cc

At some point I was surprised that when I press enter on a submenu, the
menu closes. The natural behavior (only verified after with firefox) is
Enter expands the submenu. This changes ACTION_MENU_SELECT to do just
that.
(small and nice improvement, i think)

Make ACTION_MENU_SELECT act as ENTER_SUBMENU when applicable

---

src/Config.cc
src/Frame.cc
src/Frame.hh
src/KeyboardMoveResizeEventHandler.hh
src/PDecor.cc
src/PDecor.hh
src/x11.hh

OK here's the first attempt. Only tested lightly (and seems to work) but I want to check if this is the right direction to go first. Sum up:
* Frame::setGeomtry() is broken into two pieces, the parsing/calculation and the action
* MoveResize handler now takes a Frame instead of PDecor. I'm pretty sure they are always the same when the handler is created
* MoveResize config includes parsing for SetGeometry
* MoveResize handler calls the first piece, then depending on outline mode, do the action separately
I think this is my first multiple commit PR too. Let me know if you prefer this way or just one big commit, or multiple small-and-nice PRs.
Document to be updated later.

Support SetGeometry command in MoveResize block

---

CMakeLists.txt
data/CMakeLists.txt
doc/faq.md
doc/overview.md

Locally tested in voidlinux build container
Usage: override with setting -DSYSCONFDIR=/foo
@pclouds please test how this behaves on ebuild for you
closes https://github.com/pekdon/pekwm/issues/69

Allow SYSCONFDIR override

---

data/keys
doc/actions.md
src/Action.cc
src/ActionHandler.cc
src/ActionHandler.hh

The new parameter is meant to be used in the "SendToWorkspace;
GotoWorkspace" command sequence. It makes more sense [1] that the window
you are moving remains focused and on top in the new workspace, so that
you can continue to do whatever you want with it.
This also makes it possible to move the window across multiple
workspaces fast (otherwise you would need find and focus the window
before moving again).
The name "raise" was chosen because I was thinking of
SendToWorkspace <direction>; Raise; GotoWorkspace
and actually tried that out before realizing it's "raising" one of the
windows in the current workspace, not the old one.
[1] which is also why I've updated data/keys to always use "raise" in
combination with GotoWorkspace.

Add new parameter "raise" in SendToWorkspace (#75)

---

src/Client.hh
src/PWinObj.hh
src/WindowManager.cc

The commit 974254f (Don't let new client steal focus from fullscreen
window, 2021-04-04) forbids new client from stealing focus from a
fullscreen window because the visible window in that case is still the
fullscreen window.
But that is only true when FullscreenAbove configuration is set to True,
which puts fullscreen windows on their own layer above the normal
one. If this is set to false, a fullscreen window should still be in
normal layer, and the new client should be able to show up. Which means
no need to prevent them from getting focus (and we must not because it
causes the same confusion again the other way around)

Do let clients steal focus from fullscreen sometimes

---

data/config_system
data/menu
doc/configuration.md
src/Config.cc
src/pekwm_wm.cc

This makes the system configuration files friendlier to people who do
not keep user config files at ~/.pekwm. All $_PEKWM_* variables are now
also documented.

Add $_PEKWM_CONFIG_PATH and avoid hard coding ~/.pekwm

---

src/Frame.cc
src/Frame.hh
src/PDecor.cc
src/PDecor.hh

Toggle to maximize a window, execute SetGeometry to move it in a corner,
toggle maximizing again. One would expect the window to go back
maximized because SetGeometry un-maximizes the window, but it's
not. This is the fix.
There are two versions of moveResize(). The one that takes x, y, width
and height leave maximized state handling to the callers (all in
Frame.cc it seems). The other one being updated here is used by
SetGeomtry and MoveResize commands, which I think should update
maximized state correctly.
The second version is also used by setupAPGeometry() and this is where
I'm not sure if clearing maximized state automatically is appropriate...

Correct maximized state after SetGeometry command

---

src/AutoProperties.cc

Before 44653a8 (Drop C++11 requirement from the codebase, C++98 is good
enough, 2021-04-22) workspace parse code is
unsigned(strtol((*it)->getValue().c_str(), 0, 10) - 1);
and after it:
std::stoi((*it)->getValue());
The " - 1" part got lost during the conversion. This should fix #105.

Fix off-by-one workspace numbers in placement autoprops

---

doc/overview.md

Added in Void dependencies. Note the lack of G++ in the development tools, this is because atleast in the void repos, it is simply part of the gcc package, not on its own. As far as my own limited testing goes, this works perfectly fine. Yes the captials are needed, xbps is case sensitive.

Update overview.md to include Void linux instructions.

---

src/ManagerWindows.cc
src/ManagerWindows.hh
src/Workspaces.cc

When a randr change is detected, currently we try to make sure a window
is still (partly) visible by moving it to where it can be seen. But it
just makes more sense to do a bit more for windows that we calculate
width or height automatically: maximized or fullscreen windows.
For maximized ones, while it's possible for the user to do it manually,
it's quite cumbersome (you have to unmaximize first, then resize by
keyboard; no mouse because you probably don't see the edge). For
fullscreen that's probably impossible.
So, when randr change happens, we now try to resize these windows as
well.
There are two cases this could happen. The first is resolution change
with just one monitor. I've tested this.
The second is when you have two monitor setup with different sizes and
disable the primary …

Resize fullscreen/maximized windows on randr changes

---

doc/actions.md
doc/configuration.md
src/Config.cc
src/Config.hh
src/Frame.cc
src/X11.cc
src/X11.hh

This is not an option with Xinerama. But with randr we have name on
each monitor, which is visible from xrandr or its GUI equivalents.
Selecting head by name would be easier and friendlier. More
importantly, we can also find out which screen is primary from xrandr.
This patch gets that info from randr. Harbour has a new configuration to
locate head by name. MoveToHead is also improved to accept head name in
addition to number. CurrHeadSelector could be enhanced too, but I'm not
sure if it's really useful

Support specifying harbour's head by (xrandr) name

---

src/DockApp.cc
src/InputDialog.cc
src/ManagerWindows.cc
src/PDecor.cc
src/PMenu.cc
src/StatusWindow.cc
src/WorkspaceIndicator.cc
src/X11.cc
src/X11.hh

Same PR as before except Volume buttons related changes.
Modified files cover resolving of bug caused visual artifacts after X11::createWmWindow method introduced.
X11::createWmWindow method now has _class attribute and can vary Input/InputOutput.

New PR on X11::createWmWindow

---

.dockerignore
.github/workflows/Dockerfile
.github/workflows/cmake.yml
.github/workflows/package.yml
CMakeLists.txt
nfpm.yaml.in
pkg.sh

hi!
This change adds a new workflow that, when a tag matching `release-X.Y.Z` is pushed, automatically creates releases and uploads a `.deb` build to them. goreleaser/nfpm is used to build the DEB, so we add an `nfpm.yaml` to configure it, as well.
It's easy to have the release created as a `draft` if you prefer.

auto-release deb packages

---

src/Harbour.cc
src/Harbour.hh

Commit b780659 (Fix max line-length and too many space indents, 2022-07-16) factors out the code inside Harbour::placeDockApp() into placeDockAppX and placeDockAppY but never calls the latter. Later on placeDockAppY() is deleted in another cleanup commit.
I do not understand how I only noticed this now [1] but with default harbor setting (on the right edge), all the dock apps are now moved to the left edge. And this seems to fix this, but to be honest I don't really know what I'm doing.
[1] well not now, a few months but I was too lazy to go check

Fix harbour placement on the right edge

---

src/Workspaces.cc

The current behavior is confusing. All windows are maximized. Open Emacs, Alt-tab over all windows back to Emacs. Close Emacs. The chosen window to have focus (because Emacs window is gone) is _not_ the one on top [1].
So you don't really see what window is being focused (remember all windows are maximized). Whatever you type is going to a window you cannot see.
The behavior is different if you don't just cycle through all windows.
[1] because it's chosen from MRU list, but I'm not exactly sure how MRU list is updated, when alt-tabbing. So perhaps the problem is with    updating MRU correctly.

Raise newly focused window when current one closes

---

src/Client.cc

In commit https://github.com/pekwm/pekwm/commit/89e6c9515ca6e40336f89520a594068d108e816d the ButtonReleaseMask was removed for unknown reason, readd it.
Closes issue #163

Fix ButtonRelaseMask on Client

---

src/PDecor.cc
src/PMenu.cc
src/PMenu.hh
src/ThemeGm.cc
src/lib/Iter.hh
src/lib/X11.cc
test/test.hh
test/test_PMenu.hh
test/test_pekwm.cc

GotoItem now skips separators and other non displayed menu items.

Skip all but normal menu items in GotoItem (close #175)

---

src/Frame.cc
src/InputDialog.cc
src/PDecor.cc
src/PDecor.hh
src/PMenu.cc
src/StatusWindow.cc
src/WORefMenu.cc
src/WorkspaceIndicator.cc

Seemingly other window managers do not set override_redirect on decor windows X11 clients get reparented to. To improve client compatability, and detection of what is a client window and a WM window, set this on PDecor for Frame but no other window manager windows.

Don't set override_redirect to True on non WM PDecors (Close #174)

---

NEWS.md
doc/autoproperties.md
doc/configuration.md
src/AutoProperties.cc
src/AutoProperties.hh
src/Frame.cc
src/Globals.cc
src/ManagerWindows.cc
src/WinLayouter.cc
src/WinLayouter.hh
src/WindowManager.cc
src/Workspaces.cc
src/Workspaces.hh
src/pekwm.hh
src/pekwm_wm.cc
test/test_AutoProperties.hh
test/test_Workspaces.hh
test/test_pekwm.cc

New auto property for overriding the placement for specific clients.
Example for X calculator placing it under the cursor:
Property = "^xcalc,^XCalc" {
ApplyOn = "New"
Placement = "MouseCentered"
}

Add auto property for overriding placement model
